var LEVELS = [
  { name: 'pleasant', levels: [1,2,3,4,5,6,7,8,9,10] },
  { name: 'painful', levels: [11,12,13,14,15,16,17,18,19,20] },
  { name: 'death', levels: [21,22,23,24,25,26,27,28,29,30] },
  { name: 'hell', levels: [31,32,33,34,35,36,37,38,39,40] },
  { name: 'paradise', levels: [41,42,43,44,45,46,47,48,49,50] },
  { name: 'reality', levels: [51,52,53,54,55,56,57,58,59,60] },
];

var RADICALS = [

  {"name":"Barb","symbol":"亅","level":"1"},
  {"name":"Big","symbol":"大","level":"1"},
  {"name":"Construction","symbol":"工","level":"1"},
  {"name":"Cross","symbol":"十","level":"1"},
  {"name":"Drop","symbol":"丶","level":"1"},
  {"name":"Enter","symbol":"入","level":"1"},
  {"name":"Fins","symbol":"ハ","level":"1"},
  {"name":"Ground","symbol":"一","level":"1"},
  {"name":"Gun","level":"1","symbolImage":"https://cdn.wanikani.com/subjects/images/8762-gun-large.png"},
  {"name":"Leaf","level":"1","symbolImage":"https://cdn.wanikani.com/subjects/images/8763-leaf-large.png"},
  {"name":"Lid","symbol":"亠","level":"1"},
  {"name":"Mountain","symbol":"山","level":"1"},
  {"name":"Mouth","symbol":"口","level":"1"},
  {"name":"Nine","symbol":"九","level":"1"},
  {"name":"Person","symbol":"人","level":"1"},
  {"name":"Power","symbol":"力","level":"1"},
  {"name":"Prison","symbol":"勹","level":"1"},
  {"name":"River","symbol":"川","level":"1"},
  {"name":"Seven","symbol":"七","level":"1"},
  {"name":"Slide","symbol":"丿","level":"1"},
  {"name":"Stick","level":"1","symbolImage":"https://cdn.wanikani.com/subjects/images/8761-stick-large.png"},
  {"name":"Sun","symbol":"日","level":"1"},
  {"name":"Toe","symbol":"ト","level":"1"},
  {"name":"Tree","symbol":"木","level":"1"},
  {"name":"Two","symbol":"二","level":"1"},
  {"name":"Woman","symbol":"女","level":"1"},

  {"name":"Book","symbol":"本","level":"2"},
  {"name":"Bow","symbol":"弓","level":"2"},
  {"name":"Child","symbol":"子","level":"2"},
  {"name":"Cow","symbol":"牛","level":"2"},
  {"name":"Dirt","symbol":"土","level":"2"},
  {"name":"Dog","symbol":"犬","level":"2"},
  {"name":"Evening","symbol":"夕","level":"2"},
  {"name":"Eye","symbol":"目","level":"2"},
  {"name":"Fire","symbol":"火","level":"2"},
  {"name":"Five","symbol":"五","level":"2"},
  {"name":"Flag","symbol":"尸","level":"2"},
  {"name":"Hair","symbol":"彡","level":"2"},
  {"name":"Hand","symbol":"手","level":"2"},
  {"name":"Head","symbol":"冂","level":"2"},
  {"name":"Heaven","symbol":"天","level":"2"},
  {"name":"King","symbol":"王","level":"2"},
  {"name":"Legs","symbol":"儿","level":"2"},
  {"name":"Middle","symbol":"中","level":"2"},
  {"name":"Moon","symbol":"月","level":"2"},
  {"name":"Narwhal","symbol":"ナ","level":"2"},
  {"name":"Private","symbol":"ム","level":"2"},
  {"name":"Rice Paddy","symbol":"田","level":"2"},
  {"name":"Small","symbol":"小","level":"2"},
  {"name":"Stand","symbol":"立","level":"2"},
  {"name":"Stone","symbol":"石","level":"2"},
  {"name":"Stool","symbol":"又","level":"2"},
  {"name":"Stop","symbol":"止","level":"2"},
  {"name":"Street","symbol":"丁","level":"2"},
  {"name":"Sword","symbol":"刀","level":"2"},
  {"name":"Thousand","symbol":"千","level":"2"},
  {"name":"Treasure","symbol":"メ","level":"2"},
  {"name":"Water","symbol":"水","level":"2"},
  {"name":"White","symbol":"白","level":"2"},
  {"name":"Writing","symbol":"文","level":"2"},

  {"name":"Arrow","symbol":"矢","level":"3"},
  {"name":"Canopy","symbol":"广","level":"3"},
  {"name":"Direction","symbol":"方","level":"3"},
  {"name":"Door","symbol":"戸","level":"3"},
  {"name":"Dry","symbol":"干","level":"3"},
  {"name":"Father","symbol":"父","level":"3"},
  {"name":"Fingers","symbol":"扌","level":"3"},
  {"name":"Fur","symbol":"毛","level":"3"},
  {"name":"Hat","level":"3","symbolImage":"https://cdn.wanikani.com/subjects/images/8764-hat-large.png"},
  {"name":"Heart","symbol":"心","level":"3"},
  {"name":"Life","symbol":"生","level":"3"},
  {"name":"Now","symbol":"今","level":"3"},
  {"name":"Old","symbol":"古","level":"3"},
  {"name":"Origin","symbol":"元","level":"3"},
  {"name":"Poop","symbol":"幺","level":"3"},
  {"name":"Spoon","symbol":"匕","level":"3"},
  {"name":"Task","symbol":"用","level":"3"},
  {"name":"Towel","symbol":"巾","level":"3"},
  {"name":"Triceratops","level":"3","symbolImage":"https://cdn.wanikani.com/subjects/images/8765-triceratops-large.png"},
  {"name":"Winter","symbol":"夂","level":"3"},

  {"name":"Alligator","symbol":"也","level":"4"},
  {"name":"Bamboo","symbol":"竹","level":"4"},
  {"name":"Bed","symbol":"巴","level":"4"},
  {"name":"Beggar","level":"4","symbolImage":"https://cdn.wanikani.com/subjects/images/8766-beggar-large.png"},
  {"name":"Branch","symbol":"支","level":"4"},
  {"name":"Car","symbol":"車","level":"4"},
  {"name":"Ceremony","symbol":"弋","level":"4"},
  {"name":"Cliff","symbol":"厂","level":"4"},
  {"name":"Ear","symbol":"耳","level":"4"},
  {"name":"Energy","symbol":"气","level":"4"},
  {"name":"Flowers","symbol":"艹","level":"4"},
  {"name":"Foot","symbol":"足","level":"4"},
  {"name":"Forehead","symbol":"冖","level":"4"},
  {"name":"Horns","level":"4","symbolImage":"https://cdn.wanikani.com/subjects/images/8767-horns-large.png"},
  {"name":"Insect","symbol":"虫","level":"4"},
  {"name":"Leader","symbol":"ｲ","level":"4"},
  {"name":"Loiter","symbol":"彳","level":"4"},
  {"name":"Master","symbol":"主","level":"4"},
  {"name":"Measurement","symbol":"寸","level":"4"},
  {"name":"Not","symbol":"不","level":"4"},
  {"name":"Pi","symbol":"兀","level":"4"},
  {"name":"Plate","symbol":"皿","level":"4"},
  {"name":"Red","symbol":"赤","level":"4"},
  {"name":"Rice","symbol":"米","level":"4"},
  {"name":"Roof","symbol":"宀","level":"4"},
  {"name":"Samurai","symbol":"士","level":"4"},
  {"name":"See","symbol":"見","level":"4"},
  {"name":"Shellfish","symbol":"貝","level":"4"},
  {"name":"Spikes","level":"4","symbolImage":"https://cdn.wanikani.com/subjects/images/8768-spikes-large.png"},
  {"name":"Spirit","symbol":"ネ","level":"4"},
  {"name":"Thread","symbol":"糸","level":"4"},
  {"name":"Umbrella","symbol":"乚","level":"4"},
  {"name":"World","symbol":"世","level":"4"},

  {"name":"Axe","symbol":"斤","level":"5"},
  {"name":"Blue","symbol":"青","level":"5"},
  {"name":"Coffin","symbol":"耂","level":"5"},
  {"name":"Color","symbol":"色","level":"5"},
  {"name":"Feathers","symbol":"羽","level":"5"},
  {"name":"Go","symbol":"行","level":"5"},
  {"name":"Gold","symbol":"金","level":"5"},
  {"name":"Ice","symbol":"冫","level":"5"},
  {"name":"Key","symbol":"乍","level":"5"},
  {"name":"Kick","level":"5","symbolImage":"https://cdn.wanikani.com/subjects/images/8770-kick-large.png"},
  {"name":"Lantern","symbol":"开","level":"5"},
  {"name":"Lip Ring","symbol":"可","level":"5"},
  {"name":"Meat","symbol":"肉","level":"5"},
  {"name":"Meet","symbol":"会","level":"5"},
  {"name":"Mustache","symbol":"冋","level":"5"},
  {"name":"Rain","symbol":"雨","level":"5"},
  {"name":"Run","symbol":"走","level":"5"},
  {"name":"Say","symbol":"言","level":"5"},
  {"name":"Scooter","level":"5","symbolImage":"https://cdn.wanikani.com/subjects/images/114-scooter-large.png"},
  {"name":"Self","symbol":"自","level":"5"},
  {"name":"Tsunami","symbol":"氵","level":"5"},
  {"name":"Twenty","symbol":"廾","level":"5"},
  {"name":"Viking","level":"5","symbolImage":"https://cdn.wanikani.com/subjects/images/8769-viking-large.png"},
  {"name":"Village","symbol":"里","level":"5"},
  {"name":"West","symbol":"西","level":"5"},
  {"name":"Window","symbol":"毋","level":"5"},
  {"name":"Wolverine","symbol":"ヨ","level":"5"},

  {"name":"Angel","symbol":"ホ","level":"6"},
  {"name":"Animal","symbol":"犭","level":"6"},
  {"name":"Blood","symbol":"血","level":"6"},
  {"name":"Boil","symbol":"灬","level":"6"},
  {"name":"Box","symbol":"凵","level":"6"},
  {"name":"City","symbol":"市","level":"6"},
  {"name":"Death","symbol":"亡","level":"6"},
  {"name":"Eat","symbol":"食","level":"6"},
  {"name":"Fortune","symbol":"占","level":"6"},
  {"name":"Grain","symbol":"禾","level":"6"},
  {"name":"Jet","symbol":"未","level":"6"},
  {"name":"Knife","symbol":"刂","level":"6"},
  {"name":"Lack","symbol":"欠","level":"6"},
  {"name":"Ladle","symbol":"斗","level":"6"},
  {"name":"Lion","symbol":"L","level":"6"},
  {"name":"Long","symbol":"長","level":"6"},
  {"name":"Mama","symbol":"マ","level":"6"},
  {"name":"Neck","symbol":"首","level":"6"},
  {"name":"Sheep","symbol":"羊","level":"6"},
  {"name":"Tongue","symbol":"舌","level":"6"},
  {"name":"Yakuza","symbol":"歹","level":"6"},

  {"name":"Bird","symbol":"鳥","level":"7"},
  {"name":"Black","symbol":"黒","level":"7"},
  {"name":"Boat","symbol":"舟","level":"7"},
  {"name":"Circumference","symbol":"周","level":"7"},
  {"name":"Clan","symbol":"氏","level":"7"},
  {"name":"Fish","symbol":"魚","level":"7"},
  {"name":"Gate","symbol":"門","level":"7"},
  {"name":"Husband","symbol":"夫","level":"7"},
  {"name":"Oneself","symbol":"己","level":"7"},
  {"name":"Pig","symbol":"豕","level":"7"},
  {"name":"Spear","symbol":"矛","level":"7"},
  {"name":"Stamp","symbol":"卩","level":"7"},
  {"name":"Table","symbol":"几","level":"7"},
  {"name":"Teacher","symbol":"孝","level":"7"},
  {"name":"Temple","symbol":"寺","level":"7"},
  {"name":"Top Hat","symbol":"且","level":"7"},
  {"name":"Wing","symbol":"勿","level":"7"},
  {"name":"Yellow","symbol":"黄","level":"7"},

  {"name":"Cage","symbol":"匚","level":"8"},
  {"name":"Cape","level":"8","symbolImage":"https://cdn.wanikani.com/subjects/images/8780-cape-large.png"},
  {"name":"Cloud","symbol":"云","level":"8"},
  {"name":"Compare","symbol":"比","level":"8"},
  {"name":"Easy","symbol":"易","level":"8"},
  {"name":"Hills","level":"8","symbolImage":"https://cdn.wanikani.com/subjects/images/8771-hills-large.png"},
  {"name":"Hole","symbol":"穴","level":"8"},
  {"name":"Hook","symbol":"ユ","level":"8"},
  {"name":"Horse","symbol":"馬","level":"8"},
  {"name":"Net","symbol":"罒","level":"8"},
  {"name":"Sickle","symbol":"釆","level":"8"},
  {"name":"Snake","symbol":"巳","level":"8"},
  {"name":"Suit","symbol":"合","level":"8"},
  {"name":"Weapon","symbol":"殳","level":"8"},

  {"name":"Anti","symbol":"反","level":"9"},
  {"name":"Brush","symbol":"聿","level":"9"},
  {"name":"Building","symbol":"阝","level":"9"},
  {"name":"Cleat","level":"9","symbolImage":"https://cdn.wanikani.com/subjects/images/8772-cleat-large.png"},
  {"name":"Clown","symbol":"咅","level":"9"},
  {"name":"Coat Rack","symbol":"疋","level":"9"},
  {"name":"Correct","symbol":"正","level":"9"},
  {"name":"Eternity","symbol":"永","level":"9"},
  {"name":"Gladiator","level":"9","symbolImage":"https://cdn.wanikani.com/subjects/images/8819-gladiator-large.png"},
  {"name":"Heavy","symbol":"重","level":"9"},
  {"name":"Helicopter","symbol":"覀","level":"9"},
  {"name":"History","symbol":"史","level":"9"},
  {"name":"Jammed In","symbol":"介","level":"9"},
  {"name":"Machine","symbol":"台","level":"9"},
  {"name":"Pope","level":"9","symbolImage":"https://cdn.wanikani.com/subjects/images/8773-pope-large.png"},
  {"name":"Spicy","symbol":"辛","level":"9"},
  {"name":"Spring","level":"9","symbolImage":"https://cdn.wanikani.com/subjects/images/8779-spring-large.png"},
  {"name":"Squid","level":"9","symbolImage":"https://cdn.wanikani.com/subjects/images/8785-squid-large.png"},
  {"name":"Tent","symbol":"癶","level":"9"},
  {"name":"Yurt","level":"9","symbolImage":"https://cdn.wanikani.com/subjects/images/8787-yurt-large.png"},

  {"name":"Alcohol","symbol":"酉","level":"10"},
  {"name":"Beans","symbol":"豆","level":"10"},
  {"name":"Bundle","symbol":"束","level":"10"},
  {"name":"Chinese","level":"10","symbolImage":"https://cdn.wanikani.com/subjects/images/8774-chinese-large.png"},
  {"name":"Dynamite","symbol":"丙","level":"10"},
  {"name":"Fault","symbol":"失","level":"10"},
  {"name":"Geoduck","symbol":"頁","level":"10"},
  {"name":"Kiss","symbol":"各","level":"10"},
  {"name":"Landslide","symbol":"辰","level":"10"},
  {"name":"Music","symbol":"曲","level":"10"},
  {"name":"Sell","symbol":"売","level":"10"},
  {"name":"Sick","symbol":"疒","level":"10"},
  {"name":"Stairs","symbol":"乃","level":"10"},
  {"name":"Tombstone","symbol":"圣","level":"10"},
  {"name":"Turkey","symbol":"隹","level":"10"},

  {"name":"Bear","level":"11","symbolImage":"https://cdn.wanikani.com/subjects/images/8777-bear-large.png"},
  {"name":"Blackjack","level":"11","symbolImage":"https://cdn.wanikani.com/subjects/images/8775-blackjack-large.png"},
  {"name":"Drunkard","symbol":"戈","level":"11"},
  {"name":"Escalator","symbol":"及","level":"11"},
  {"name":"Few","symbol":"少","level":"11"},
  {"name":"Humble","symbol":"申","level":"11"},
  {"name":"Older Brother","symbol":"兄","level":"11"},
  {"name":"Orders","symbol":"令","level":"11"},
  {"name":"Root","symbol":"艮","level":"11"},
  {"name":"Simple","symbol":"単","level":"11"},
  {"name":"Skin","symbol":"皮","level":"11"},
  {"name":"Sound","symbol":"音","level":"11"},
  {"name":"Trash","level":"11","symbolImage":"https://cdn.wanikani.com/subjects/images/8776-trash-large.png"},

  {"name":"Asia","symbol":"亜","level":"12"},
  {"name":"Beforehand","symbol":"予","level":"12"},
  {"name":"Business","symbol":"業","level":"12"},
  {"name":"Crab","symbol":"其","level":"12"},
  {"name":"Early","symbol":"早","level":"12"},
  {"name":"Excuse","symbol":"免","level":"12"},
  {"name":"Fix","symbol":"直","level":"12"},
  {"name":"Jackhammer","symbol":"示","level":"12"},
  {"name":"Request","symbol":"求","level":"12"},
  {"name":"Someone","symbol":"者","level":"12"},
  {"name":"Tofu","level":"12","symbolImage":"https://cdn.wanikani.com/subjects/images/8778-tofu-large.png"},
  {"name":"Together","symbol":"共","level":"12"},
  {"name":"Yoga","symbol":"廴","level":"12"},
  {"name":"Younger Brother","symbol":"弟","level":"12"},

  {"name":"Body","symbol":"身","level":"13"},
  {"name":"Bookshelf","symbol":"冊","level":"13"},
  {"name":"Center","symbol":"央","level":"13"},
  {"name":"Circle","symbol":"丸","level":"13"},
  {"name":"Creeper","level":"13","symbolImage":"https://cdn.wanikani.com/subjects/images/8781-creeper-large.png"},
  {"name":"East","symbol":"東","level":"13"},
  {"name":"Elephant","symbol":"象","level":"13"},
  {"name":"Fruit","symbol":"果","level":"13"},
  {"name":"Good","symbol":"良","level":"13"},
  {"name":"Hundred","symbol":"百","level":"13"},
  {"name":"Idea","symbol":"意","level":"13"},
  {"name":"Original","symbol":"原","level":"13"},
  {"name":"Products","symbol":"品","level":"13"},
  {"name":"Scarecrow","symbol":"畐","level":"13"},
  {"name":"Shrimp","symbol":"尺","level":"13"},
  {"name":"Soul","symbol":"忄","level":"13"},
  {"name":"Womb","symbol":"坴","level":"13"},

  {"name":"Bar","level":"14","symbolImage":"https://cdn.wanikani.com/subjects/images/8782-bar-large.png"},
  {"name":"Genius","symbol":"才","level":"14"},
  {"name":"Part","symbol":"分","level":"14"},
  {"name":"Pool","symbol":"勺","level":"14"},
  {"name":"Public","symbol":"公","level":"14"},
  {"name":"Well","symbol":"井","level":"14"},

  {"name":"Grass","level":"15","symbolImage":"https://cdn.wanikani.com/subjects/images/8783-grass-large.png"},
  {"name":"Height","symbol":"丈","level":"15"},
  {"name":"Man","symbol":"男","level":"15"},
  {"name":"Paragraph","symbol":"句","level":"15"},
  {"name":"Past","symbol":"去","level":"15"},
  {"name":"Saw","level":"15","symbolImage":"https://cdn.wanikani.com/subjects/images/241-saw-large.png"},
  {"name":"Walk","symbol":"歩","level":"15"},

  {"name":"Attach","symbol":"付","level":"16"},
  {"name":"Drum","symbol":"壴","level":"16"},
  {"name":"Face","symbol":"面","level":"16"},
  {"name":"Valley","symbol":"谷","level":"16"},
  {"name":"Zombie","level":"16","symbolImage":"https://cdn.wanikani.com/subjects/images/8784-zombie-large.png"},

  {"name":"Comfort","symbol":"楽","level":"17"},
  {"name":"Criminal","symbol":"非","level":"17"},
  {"name":"Festival","symbol":"祭","level":"17"},
  {"name":"Good Luck","symbol":"吉","level":"17"},
  {"name":"Guard","symbol":"兑","level":"17"},
  {"name":"Nothing","symbol":"無","level":"17"},
  {"name":"Poem","symbol":"苟","level":"17"},
  {"name":"Tiger","symbol":"虍","level":"17"},

  {"name":"Conflict","symbol":"争","level":"18"},
  {"name":"Gambler","symbol":"尭","level":"18"},
  {"name":"Happiness","symbol":"幸","level":"18"},
  {"name":"Long Ago","symbol":"昔","level":"18"},
  {"name":"Mask","symbol":"曽","level":"18"},
  {"name":"Noon","symbol":"午","level":"18"},
  {"name":"Previous","symbol":"先","level":"18"},
  {"name":"Treasure Chest","symbol":"凶","level":"18"},

  {"name":"Become","symbol":"成","level":"19"},
  {"name":"Black Hole","symbol":"复","level":"19"},
  {"name":"Director","symbol":"司","level":"19"},
  {"name":"Ego","symbol":"我","level":"19"},
  {"name":"Feeling","symbol":"感","level":"19"},
  {"name":"Reason","symbol":"由","level":"19"},
  {"name":"Right","symbol":"右","level":"19"},

  {"name":"Explosion","level":"20","symbolImage":"https://cdn.wanikani.com/subjects/images/8788-explosion-large.png"},
  {"name":"Flood","symbol":"巛","level":"20"},
  {"name":"Fly","symbol":"飛","level":"20"},
  {"name":"Mole","symbol":"至","level":"20"},
  {"name":"Mona Lisa","symbol":"兼","level":"20"},
  {"name":"Righteousness","symbol":"義","level":"20"},

  {"name":"Angle","symbol":"角","level":"21"},
  {"name":"Blade","symbol":"刃","level":"21"},
  {"name":"Half","symbol":"半","level":"21"},
  {"name":"Mohawk","symbol":"啇","level":"21"},
  {"name":"Next","symbol":"次","level":"21"},
  {"name":"Number","symbol":"番","level":"21"},
  {"name":"Peace","symbol":"平","level":"21"},
  {"name":"Simultaneous","symbol":"斉","level":"21"},

  {"name":"Ability","symbol":"能","level":"22"},
  {"name":"Allocate","symbol":"充","level":"22"},
  {"name":"Bathtub","symbol":"呂","level":"22"},
  {"name":"Cheap","symbol":"安","level":"22"},
  {"name":"Dollar","symbol":"弗","level":"22"},
  {"name":"Football","symbol":"爰","level":"22"},
  {"name":"Icicle","symbol":"丬","level":"22"},

  {"name":"Clothes","symbol":"衣","level":"23"},
  {"name":"Demon","symbol":"鬼","level":"23"},
  {"name":"Leather","symbol":"革","level":"23"},
  {"name":"Morning","level":"23","symbolImage":"https://cdn.wanikani.com/subjects/images/8793-morning-large.png"},
  {"name":"Restaurant","symbol":"亭","level":"23"},
  {"name":"Road","symbol":"道","level":"23"},
  {"name":"Vines","symbol":"丩","level":"23"},

  {"name":"Accept","symbol":"受","level":"24"},
  {"name":"Control","symbol":"制","level":"24"},
  {"name":"Dawn","symbol":"旦","level":"24"},
  {"name":"Death Star","level":"24","symbolImage":"https://cdn.wanikani.com/subjects/images/8790-death-star-large.png"},
  {"name":"Guest","symbol":"客","level":"24"},
  {"name":"Korea","symbol":"韋","level":"24"},
  {"name":"Nature","symbol":"然","level":"24"},

  {"name":"Both","symbol":"両","level":"25"},
  {"name":"Capital","symbol":"京","level":"25"},
  {"name":"Friend","symbol":"友","level":"25"},
  {"name":"Greenhouse","symbol":"莫","level":"25"},
  {"name":"Lifeguard","symbol":"冓","level":"25"},
  {"name":"Mantis","symbol":"禹","level":"25"},
  {"name":"Mix","symbol":"交","level":"25"},
  {"name":"Wedding","symbol":"甫","level":"25"},

  {"name":"Announce","symbol":"告","level":"26"},
  {"name":"Chapter","symbol":"章","level":"26"},
  {"name":"Comb","level":"26","symbolImage":"https://cdn.wanikani.com/subjects/images/8792-comb-large.png"},
  {"name":"Ten Thousand","symbol":"万","level":"26"},
  {"name":"Warehouse","symbol":"倉","level":"26"},

  {"name":"Call","symbol":"召","level":"27"},
  {"name":"Change","symbol":"化","level":"27"},
  {"name":"Exit","symbol":"出","level":"27"},
  {"name":"Farming","symbol":"農","level":"27"},
  {"name":"Peoples","symbol":"民","level":"27"},
  {"name":"Rake","symbol":"而","level":"27"},
  {"name":"Substitute","symbol":"代","level":"27"},
  {"name":"Surplus","symbol":"余","level":"27"},

  {"name":"Barracks","symbol":"屯","level":"28"},
  {"name":"Giant","symbol":"巨","level":"28"},
  {"name":"Lovely","symbol":"麗","level":"28"},
  {"name":"Odd","symbol":"奇","level":"28"},
  {"name":"Specialty","symbol":"専","level":"28"},

  {"name":"Above","symbol":"上","level":"29"},
  {"name":"Blame","symbol":"責","level":"29"},
  {"name":"Charcoal","symbol":"尞","level":"29"},
  {"name":"District","symbol":"区","level":"29"},
  {"name":"Nose","symbol":"乙","level":"29"},
  {"name":"Servant","symbol":"臣","level":"29"},

  {"name":"Lineage","symbol":"系","level":"30"},
  {"name":"North","symbol":"北","level":"30"},
  {"name":"One Sided","symbol":"片","level":"30"},
  {"name":"Oversee","symbol":"監","level":"30"},
  {"name":"Pirate","symbol":"冘","level":"30"},
  {"name":"Turtle Shell","symbol":"甲","level":"30"},

  {"name":"Bully","symbol":"鬲","level":"31"},
  {"name":"Fang","symbol":"牙","level":"31"},
  {"name":"Guy","symbol":"郎","level":"31"},
  {"name":"Library","symbol":"扁","level":"31"},
  {"name":"Line Up","symbol":"並","level":"31"},
  {"name":"Rocket","symbol":"离","level":"31"},

  {"name":"Cat Pirate","symbol":"卬","level":"32"},
  {"name":"Certain","symbol":"必","level":"32"},
  {"name":"Cottage","symbol":"舎","level":"32"},
  {"name":"Elf","level":"32","symbolImage":"https://cdn.wanikani.com/subjects/images/8799-elf-large.png"},
  {"name":"Night","symbol":"夜","level":"32"},
  {"name":"Same","symbol":"同","level":"32"},
  {"name":"Spider","symbol":"夋","level":"32"},

  {"name":"Coral","level":"33","symbolImage":"https://cdn.wanikani.com/subjects/images/8794-coral-large.png"},
  {"name":"Inside","symbol":"内","level":"33"},
  {"name":"Interval","symbol":"間","level":"33"},
  {"name":"Sock","symbol":"享","level":"33"},
  {"name":"Storehouse","symbol":"蔵","level":"33"},
  {"name":"Syrup","symbol":"喿","level":"33"},
  {"name":"Wide","symbol":"広","level":"33"},

  {"name":"Boot","symbol":"堇","level":"34"},
  {"name":"Catapult","symbol":"呉","level":"34"},
  {"name":"Claw","symbol":"爪","level":"34"},
  {"name":"Member","symbol":"員","level":"34"},
  {"name":"Slice","symbol":"亥","level":"34"},

  {"name":"Belt","symbol":"帯","level":"35"},
  {"name":"Commander","symbol":"将","level":"35"},
  {"name":"Sake","symbol":"為","level":"35"},
  {"name":"Shuriken","symbol":"彑","level":"35"},
  {"name":"Turtle","symbol":"亀","level":"35"},

  {"name":"Bright","symbol":"明","level":"36"},
  {"name":"Dance","symbol":"舛","level":"36"},
  {"name":"Departure","symbol":"発","level":"36"},
  {"name":"South","symbol":"南","level":"36"},
  {"name":"Sweet","symbol":"甘","level":"36"},
  {"name":"Valuable","symbol":"貴","level":"36"},

  {"name":"Omen","symbol":"兆","level":"37"},
  {"name":"Prize","symbol":"賞","level":"37"},
  {"name":"Skewer","symbol":"串","level":"37"},
  {"name":"Violence","symbol":"暴","level":"37"},
  {"name":"Wrap","symbol":"包","level":"37"},

  {"name":"Have","symbol":"有","level":"38"},
  {"name":"Hot Pepper","symbol":"辟","level":"38"},
  {"name":"Prefecture","symbol":"県","level":"38"},
  {"name":"Sky","symbol":"空","level":"38"},
  {"name":"Think","symbol":"思","level":"38"},
  {"name":"Tooth","symbol":"歯","level":"38"},

  {"name":"Buddy","symbol":"君","level":"39"},
  {"name":"Former","symbol":"旧","level":"39"},
  {"name":"Hill","symbol":"岡","level":"39"},
  {"name":"Nurse","symbol":"㐮","level":"39"},
  {"name":"Reality","symbol":"真","level":"39"},
  {"name":"Scroll","symbol":"巻","level":"39"},
  {"name":"Three","symbol":"三","level":"39"},

  {"name":"Employ","symbol":"雇","level":"40"},
  {"name":"Every","symbol":"毎","level":"40"},
  {"name":"Preserve","symbol":"保","level":"40"},
  {"name":"Rejoice","symbol":"喜","level":"40"},

  {"name":"Cactus","level":"41","symbolImage":"https://cdn.wanikani.com/subjects/images/8796-cactus-large.png"},
  {"name":"Signpost","symbol":"夆","level":"41"},
  {"name":"Wife","symbol":"妻","level":"41"},

  {"name":"Bone","symbol":"骨","level":"42"},
  {"name":"Melon","symbol":"瓜","level":"42"},
  {"name":"Satellite","level":"42","symbolImage":"https://cdn.wanikani.com/subjects/images/8798-satellite-large.png"},
  {"name":"Shop","symbol":"屋","level":"42"},

  {"name":"Badger","symbol":"豸","level":"43"},
  {"name":"Imperial","symbol":"龍","level":"43"},
  {"name":"Plow","symbol":"耒","level":"43"},

  {"name":"Can","symbol":"缶","level":"44"},
  {"name":"Dragon","symbol":"竜","level":"44"},
  {"name":"Wind","symbol":"風","level":"44"},

  {"name":"Again","symbol":"更","level":"45"},
  {"name":"House","symbol":"家","level":"45"},
  {"name":"Protect","symbol":"守","level":"45"},

  {"name":"Fat","symbol":"太","level":"46"},
  {"name":"Favor","symbol":"恵","level":"46"},

  {"name":"Penguin","symbol":"敝","level":"47"},
  {"name":"Wave","symbol":"波","level":"47"},

  {"name":"Form","symbol":"容","level":"48"},
  {"name":"Mysterious","symbol":"玄","level":"48"},
  {"name":"Sunlight","symbol":"光","level":"48"},

  {"name":"Crab Trap","symbol":"甚","level":"49"},
  {"name":"Times","symbol":"回","level":"49"},
  {"name":"Wild","symbol":"荒","level":"49"},

  {"name":"Name","symbol":"名","level":"50"},
  {"name":"Psychopath","level":"50","symbolImage":"https://cdn.wanikani.com/subjects/images/8797-psychopath-large.png"},
  {"name":"Splinter","symbol":"禺","level":"50"},

  {"name":"Stomach","symbol":"胃","level":"51"},

  {"name":"Frostbite","symbol":"夌","level":"52"},

  {"name":"Tall","symbol":"高","level":"53"},

  {"name":"Doubt","symbol":"疑","level":"55"},

  {"name":"Concave","symbol":"凹","level":"57"},
  {"name":"Convex","symbol":"凸","level":"57"},

  {"name":"Below","symbol":"下","level":"59"},

  {"name":"Courage","symbol":"勇","level":"60"}
];
